name: Update GitHub Activity Graph

on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 自动更新
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate activity graph
        uses: Ashutosh00710/github-readme-activity-graph@master
        with:
          USERNAME: DestinyDevL
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
