name: Update GitHub Readme Stats

on:
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch: # 可手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: "Update README with the recent activity"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


        
